### PR TITLE
Added check on constant definition

### PR DESCRIPTION
**Pull request by gnugat**
This is a naive attempt to solve issue puli/issues#47

### CODE REVIEW

**Comment by gnugat** [comment]
Looks like there's an issue: the test suite for hhvm doesn't pass, it gets the following error

```
Fatal error: Class undefined: PHP_Token_HASHBANG
```

I'm not sure if I can do anything about it though.

**Comment by gnugat** [comment]
Ping @webmozart

**Comment by gnugat** [comment]
Looks like the fail is caused by an issue in hhvm itself (see https://github.com/facebook/hhvm/issues/4810).

**Comment by webmozart** [comment]
Hi! Sorry for the wait, this looks good :) Thanks!

**Comment by gnugat** [comment]
Cheers, can't wait for puli to be 1.0.0@stable :)

**Pull request merged**
