### PR TITLE
[WIP] Fix windows problems

### PR DESCRIPTION
**Pull request by temp**
Fixes problems 1+2 from puli/puli#102

### CODE REVIEW

**Comment by webmozart** [comment]
Thanks for the PR @temp! I think it would be better if you replaced the single quotes with double quotes, which are the proper way of escaping parameters on Windows. Can you change that?

**Comment by temp** [comment]
Will have a look into it. If I remember correctly, we tried that, and it didn't work.

**Comment by temp** [comment]
Ok, works, switched to double quotes.

**Comment by temp** [comment]
Created a new PR, #18.

**Pull request closed without merging**
